# Generated by Django 5.2.8 on 2026-01-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chapter'),
        ('engagement', '0002_alter_classengagement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classengagement',
            name='start_time',
        ),
        migrations.AddField(
            model_name='classengagement',
            name='hours_taken',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='classengagement',
            name='is_extra_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classengagement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classengagement',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chapter'),
        ),
        migrations.AlterField(
            model_name='classengagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
