# Generated by Django 5.2.8 on 2025-11-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicsession_remove_chapter_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester'),
        ),
    ]
