# Generated by Django 5.2.8 on 2025-11-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_department_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlog',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.chapter'),
            preserve_default=False,
        ),
    ]
