# Generated by Django 5.2.8 on 2025-11-27 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_classlog_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlog',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(80.0)]),
        ),
    ]
