# Generated by Django 5.2.8 on 2026-01-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_semester_batch_remove_semester_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicContext',
        ),
    ]
